### ISSUE TITLE
Failed to download file ..

### ISSUE THREAD

**Issue by natocTo** [keboola/input-mapping#33]
K diskuzi.

Přistál mi k tomu ticket na zendesku, že to je asi nějaký expirovaný soubor, zda takové soubory nejde nějak přeskočit.

Zendesk: (je tam odkaz na job)
https://keboola.zendesk.com/agent/tickets/10436

Chyba:
https://connection.keboola.com/admin/utils/logs?file=2019/05/02/19/2019-05-02-19-46-05-5ccb2cdd87bb5-exception

**Comment by ujovlado** [comment]
To bude toto https://github.com/keboola/input-mapping/issues/18 -> t.j to issue 1080 na connection (mam to assignute, budem sa tomu venovat myslim bud. tyzden)

**Comment by natocTo** [comment]
Super dík za info, tak zavírám.
