### ISSUE TITLE
Support table input mapping by tags

### ISSUE THREAD

**Issue by odinuv** [keboola/input-mapping#37]
Given a metadata tag, the input mapping should load all tables with that tag, 

depends on https://github.com/keboola/connection/issues/2184

**Comment by zajca** [comment]
Díval sem sa na to úplně mě není jasná flow toho input-mappingu. 

Předpokládám, že bude asi potřeba přidat `Table` další klíč něco jako `medataSource` a všude v readeru před `$table->getSource()` přidat check jestli to není v metadatech a kdyžtak stáhnout tabulku, pokud to teda chápu správně.

Ještě mě napadlo, jestli by tu konfiguraci nemohl řešit třebas preprocessor, ale ten tuším neví, která komponenta ho pustila.

**Comment by odinuv** [comment]
> Díval sem sa na to úplně mě není jasná flow toho input-mappingu.

IM jako takovej zadny flow nema, to je az o level nebo dva vejs - tady https://github.com/keboola/docker-bundle/blob/9ba88e74509141871b0eea3d5f19d65f650cc1f8/src/Docker/Runner.php#L400
- z cehoz taky vyplyva, ze na to nejde pouzit preprocesory, protoze ty se aplikuji az na hotovej IM pro komponentu

> Předpokládám, že bude asi potřeba přidat Table další klíč něco jako medataSource a 

tak neco

> všude v readeru před $table->getSource() přidat check jestli to není v metadatech a kdyžtak stáhnout tabulku, pokud to teda chápu správně.

z toho bysme se pokakali

Dulezity je, ze jedna tabulka je vzdycky jeden destination, cili mame

```
"tables": [
    {
        "source": "in.c-main.my-table",
        "destination": "my-table.csv
    }
]
```

a rozsiril bych to pridanim `search_source` na:

```
"tables": [
    {
        "search_source": {
             "search_by": "table",
             "key": "my.metadata.key",
             "value": "my.value"
         },
        "destination": "my-table.csv
    }
]
```

otazka je co kdyz ten search vrati vic tabulek - a jsou dve moznosti - bud failnout, nebo tabulky importovat do jedne - tj. povazovat je za slicy (technicky to znamena vyhodit z nich headery a ulozit je do podadresare). Pro jednoduchost ted urcite volime jednu, cili failne to s user errorem, ze to je nejednoznacny. V kazdym pripade porad ale plati dulezitej zachytnej bod a sice ze jedna polozka v konfiguraci `tables` je jedna tabulka pro komponentu. Tzn. semka https://github.com/keboola/input-mapping/blob/5813b47f2948efec289a6ee2b8ef801e78d5b818/Reader/Reader.php#L263
bych predradil neco jako `$this->resolve($tablesDefinition)` co vezme kazdou table definition, podiva se jestli je v ni search_source, pokud jo, tak to pretavi na id tabulky a pokud jich bude vic tak failne, a to potom vrati jako novy tablesdefinition

takhle by to melo jit udelat hladce, pak samozrejme ta dalsi verze s tema slicama bude slozitejsi, ale tam je vic veci - treba adaptivni im https://github.com/keboola/input-mapping/blob/5813b47f2948efec289a6ee2b8ef801e78d5b818/Reader/Reader.php#L265 kterej by tam nefungoval a s3 staging, takze bych se do toho ted vubec nepoustel

**Comment by zajca** [comment]
K čemu je dobrý ten `search_by`?

**Comment by odinuv** [comment]
viz https://github.com/keboola/input-mapping/pull/39#discussion_r328111443 zatim bych to klido vyhodil

**Comment by zajca** [comment]
Ještě mě napadlo jestli nevynucovat nějaký specifický klíč ať je v tom větší pořádek třeba `kbc.mapping.tag` nebo zavést nějaké obecné pravidla čím by se měli ty klíče a hodnoty obecně řídit, aby když budem hledat někde třeba zádrhel aby to bylo jednodušší filtrovat.

**Comment by odinuv** [comment]
nn, to bych nedelal, input-mapping je hodne obecna komponenta a nejaky bdm je tomu uplne u riti. Dulezity je, aby to dobre logovalo a pak se bude dat zjistit kde je zadrhel.
