### ISSUE TITLE
Internal error if all columns are numeric

### ISSUE THREAD

**Issue by Halama** [keboola/input-mapping#44]
Error: `The attribute \"name\" must be set for path \"table.column_metadata\"."`
- client error: https://keboola.slack.com/archives/C09U3R1J4/p1572609895006700
- simulated: 
  - error: https://keboola.slack.com/archives/C09U3R1J4/p1572611087007600
  - config: https://connection.keboola.com/admin/projects/4088/jobs/547396703

### How To Simulate
1. Create table with columns `1,2,3`
2. Configure e.g. google sheets writer with table from previous step

![image](https://user-images.githubusercontent.com/903531/68024813-7b50a280-fcab-11e9-9dfb-cfc9a68012ce.png)

**Comment by ErikZigo** [comment]
Merged into another issue in Jira https://keboola.atlassian.net/browse/PS-3324
